name: Build & Deploy

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Determine yarn cache location
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Upload CI Environment
      uses: actions/upload-artifact@v1
      with:
        name: ci-environment
        path: .

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:

      - name: Load CI Environment
        uses: actions/download-artifact@v1
        with:
          name: ci-environment

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Upload Built Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Load CI Environment
      uses: actions/download-artifact@v1
      with:
        name: ci-environment

    - name: Load Built Artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist

    - name: Deploy
      run: yarn deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
